### ISSUE TITLE
[SDL 0118] Video Streaming Backgrounded String

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_ios#1058]
Proposal: [Video Streaming Backgrounded String](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0118-video-background-string.md)

> Display a string of text on the head unit screen when the app leaves the foreground.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/356

Steering Committee Decision:

> The Steering Committee voted to accept this proposal with revisions. The revisions will include updating the text to reflect Ford legal's preference, as described in this comment from Ford.  There was also discussion on the call regarding translations of this text. It was determined these could be discussed at a later date upon implementation, but would likely not require a separate Evolution Proposal for review.
> The proposal .md file was updated to reflect these revisions on 8/27/18.

**Comment by t-yoshii** [comment]
Hi, 

We tested this functionality on our HU (sdl_ios v6.2). 

Since our HMI hides video window after SDL Core sends OnVideoDataStreaming(false) to HMI, therefore, this string is only shown during video streaming timeout duration (3000 msec). I think this is not user-friendly and is not good for driver distraction because the display contents frequently change in a short period of time (VPM => message string => black).  On SYNC, is this message kept showing after the OnVideoDataStreaming(false) is sent to HMI?

Additionally, this string shows English only.

We would like to add functionality to disable this feature or functionality to change the display string (to set empty string will also disable this)
Can we create an issue and PR? Or do we have to create a proposal?

Our HU has a capability to change the display layout other than Navigation template, so even VPM app can show Non-Media template and can show a "bring app to foreground" like string by Show RPC.

Thank you

**Comment by MichaelCrimando** [comment]
@t-yoshii I can at the very least comment on SYNC3 - the background string just stays on the screen with no timeout that I can tell (only tried under a minute)

**Comment by joeljfischer** [comment]
Hi @t-yoshii, it's unfortunate to hear that you're hiding the window in this way after 3 seconds. I agree that this causes a sub-optimal user-experience for your system.

First, however, I'd like to note that this proposal has been accepted for quite a long time, and therefore your solution of hiding the window when the video stream is paused would certainly have been discouraged had it been known earlier in this process. I suppose that's why Core Certification is so important.

Regarding possible solutions, nothing can be done without a proposal. This functionality was proposed, reviewed, and accepted by the SDLC, so changing it requires the same process.

> We would like to add functionality to disable this feature or functionality to change the display string (to set empty string will also disable this)

To be clear, this would have to be an API that a developer would _only change _if they know for a fact that the connected head unit performs bad behavior with the background string_ (such as in your case. Changing the string cannot currently happen, because OEMs then have to validate whatever the app chooses to display on the screen (this was the reason for years of delays on this proposal being implemented in the first place). So a developer would only have the ability to disable it, and they would have to do so by checking the RAIR data to see if the connected head unit is one they _know_ performs badly with the background string (e.g. by investigating the make / model / trim).

> Additionally, this string shows English only.

It was accepted this way due to the need to use translation services. If you want to propose a list of languages that the string can be translated into, we can investigate the cost of using a translation service to create strings for each language.

> Our HU has a capability to change the display layout other than Navigation template, so even VPM app can show Non-Media template and can show a "bring app to foreground" like string by Show RPC.

I strongly recommend that you do not follow this path.

---

Let me know if we can help further in any way.

**Comment by t-yoshii** [comment]
@joeljfischer 
Thank you very much for your detailed comments.

> To be clear, this would have to be an API that a developer would only change if they know for a fact that the connected head unit performs bad behavior with the background string (such as in your case). Changing the string cannot currently happen, because OEMs then have to validate whatever the app chooses to display on the screen (this was the reason for years of delays on this proposal being implemented in the first place). So a developer would only have the ability to disable it, and they would have to do so by checking the RAIR data to see if the connected head unit is one they know performs badly with the background string (e.g. by investigating the make / model / trim).

Yes, I agree with this. App should check RAIR (this stands for RegisterAppInterface response, right?).
I would like to write a proposal to add a feature to offer an option to app developer to disable "video streaming background string" feature.


BTW,

> First, however, I'd like to note that this proposal has been accepted for quite a long time, and therefore your solution of hiding the window when the video stream is paused would certainly have been discouraged had it been known earlier in this process. I suppose that's why Core Certification is so important.
> I strongly recommend that you do not follow this path.

Why is hiding video window and showing other template in Navi app discouraged?
I think that showing non-VPM contents in some situation is a reasonable solution. It can be a workaround when video is not available for some reason on HS (including app inactive) by showing alternative navigation contents by template mode.

**Comment by joeljfischer** [comment]
> Why is hiding video window and showing other template in Navi app discouraged?
I think that showing non-VPM contents in some situation is a reasonable solution. It can be a workaround when video is not available for some reason on HS (including app inactive) by showing alternative navigation contents by template mode.

I apologize for the confusion. I wasn't referring to showing a template _in principle_. I was referring to showing a template when the video streaming app goes into the background (the situation that the video streaming string is shown). There should be _one_ way that backgrounding the app works across SDL head units and apps to create predictability for the user.
