### ISSUE TITLE
Setting a `SDLArtwork`'s `overwrite` property to true does not work with screen manager

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/sdl_ios#1117]
### Bug Report
If an artwork with the same name is uploaded using the screen manager with `overwrite` set to `true` and `persistent` set to `false`, the new artwork is not shown. 

##### Reproduction Steps
1. Connect app to Core
1. Send a show request with the `graphic` set to an artwork named "TestArtwork"
1. Send a second show request with the `graphic` set  to a different artwork also named "TestArtwork". Set the artwork's `overwrite` property to `true` and `persistent` property to `false`.

##### Expected Behavior
The new artwork will show up in the `graphic` field of the template.

##### Observed Behavior
The `graphic` field of the template shows the old artwork.

##### OS & Version Information
* iOS Version: 12
* SDL iOS Version: 6.1
* Testing Against: SYNC 3

**Comment by NicoleYarroch** [comment]
Bug reporter said new artworks are sent every 2 seconds so it might be an issue with the screen manager delaying sending new RPCs until it has gotten a response from Core.

**Comment by NicoleYarroch** [comment]
The ScreenManager uses the image name to determine whether or not to upload the image. It never checks if the overwrite property is true so if an image with the same name is sent to the screen manager, it will assume that the image has already been uploaded and will not attempt to upload the new image data.

**Comment by NicoleYarroch** [comment]
This turned out to be an issue with the SDL_iOS library and with SDL_Core. There is a [proposal](https://github.com/smartdevicelink/sdl_evolution/pull/631) to fix the Core issue that must be approved and implemented before the iOS library can be fixed.

**Comment by E-SAITO-TMC** [comment]
@joeljfischer -san, We were able to reproduce this issue with v6.5.0. This is a medium priority issue for Toyota. Is it possible to include this in the next release plan?

**Comment by joeljfischer** [comment]
@E-SAITO-TMC Thank you for letting us know about this issue's priority for you. The underlying Core issue was fixed in SDL Core v6.0 [proposal here](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0212-add-ability-to-reuse-a-syncfilename-for-a-putfile.md).

However, there is an additional dependency the maintainers consider vital, which is to refactor the `SDLTextAndGraphicManager` to use queues instead of the current architecture. That requires a fair bit of work, and the Java_Suite team cannot currently align to perform the same work. There is an upcoming proposal to allow the Java_Suite team to use queues in a similar way to the iOS library, but that dependency means that this bug will need to wait until the Fall release at the earliest before it is fixed.

**Comment by E-SAITO-TMC** [comment]
@joeljfischer -san, Thank you for reply. I understand. Please let me know if this status changes.
