### ISSUE TITLE
 iOS 12+ Video Streaming Performance Issue

### ISSUE THREAD

**Issue by GauravPandey321** [smartdevicelink/sdl_ios#1151]
**[Summary]**
We tested navigation app e.g. Waze for performance, responsiveness and video quality over different iPhone models with different version of iOS 12. 

**[Test Steps performed]**
              1. Connect the iPhone with the head unit via Bluetooth and/or USB.
              2. Ensure Waze connects with SDL Core
              3. Launch the navigation app i.e. Waze

**[Expected Behavior]**
Navigation app performance should be at an acceptable level across all supported devices (performance may slightly differ based on handset capabilities).

**[Observed Behavior]**
We observed Waze behaving more sluggishly and performing poorly when we tested on iPhone 8 running iOS 12.0. The app was slow, less responsive and video lagging on touch input. The performance was much improved with better user experience when tested on iOS 12.1 and 11.0.3 as well as older (iPhone 6S) and newer (iPhone XS) devices. See attached video. 

| i0S ver | Handset iPhone | Waze User Experience | Remark |
| ------- | ---------------- | ---------------------- | -------- |
| 12.1      | 6S                       | Good                           | Video runs smoothly |  
| 12.0      | 8+                      | Poor                             | Video sluggish & lagging |  
| 12.0      | XS                      | Poor                             | Video sluggish & lagging |  
| 12.0      | 6S+                    | Passable                      | Low framerate but useable |  
| 11.0.3   | 8+                      | Good                           | Video sluggish & lagging |  

**[Analysis]**
From our internal testing applications, it seems that the “drawViewHeirarchyInRect” function is causing the degradation of performance on some devices on iOS 12.0.  The issue seems to be improved in iOS 12.1.  Utilizing the “renderInContext” function as an alternative to “drawViewHeirarchyInRect” seems to improve the performance issue but may have some limitations with OpenGL and other methodologies used by navigation partners for video streaming.  Additionally, the following proposal in review may also resolve the issue:
([https://github.com/smartdevicelink/sdl_evolution/issues/661](https://github.com/smartdevicelink/sdl_evolution/issues/661))

**[Notes]**
This issue may be related to the follow issue:
([https://github.com/smartdevicelink/sdl_evolution/issues/2766](https://github.com/smartdevicelink/sdl_evolution/issues/2766))

**[Video]**
[(Navigation app on iPhone)](https://mydocs.toyota.com/:v:/r/personal/gaurav_pandey_toyota_com/Documents/Waze_Performance_20190129.mp4?csf=1&e=yW2vah))

**Comment by jordynmackool** [comment]
In the Steering Committee meeting on 2019-03-15 the PM referenced [this comment](https://github.com/smartdevicelink/sdl_ios/issues/1151#issuecomment-465181744) noting that the problem is most likely an Apple iOS issue and recommended that if user's on iOS 12.0 are reporting poor performance, the best thing to do for now is to recommend that they update to iOS 12.1+. 

- Toyota agreed that performance on 12.1 and above seemed to improve. 

- Toyota requested that SDLC members continue to investigate better ways to improve video streaming performance on iOS as currently the UX is not great. It was additionally requested that this becomes a high priority for the SDLC and if any members find solutions to please put forth a proposal.
