### ISSUE TITLE
Wrong value type of language parameter of SDLRegisterAppInterfaceResponse

### ISSUE THREAD

**Issue by mvyrko** [smartdevicelink/sdl_ios#1159]
### Bug Report
In function `- (void)didEnterStateRegistered` when we try to check condition `[actualLanguage isEqualToEnum:desiredLanguage]` we crash with `[__NSCFNumber isEqualToEnum:]: unrecognized selector sent to instance`

##### Expected Behavior
No crash

##### Observed Behavior
Crash

##### OS & Version Information
* iOS Version: Any
* SDL iOS Version: 6.1.0

##### Test Case, Sample Code, and / or Example App
![screen shot 2019-02-08 at 2 55 56 pm](https://user-images.githubusercontent.com/11045737/52477100-cd97e380-2bb1-11e9-80f0-71995124c215.png)

**Comment by NicoleYarroch** [comment]
@mvyrko It would be really useful to see the `RegisterAppInterface` response being returned by the head unit. 
From the bugs you have reported, it looks like the head unit manufacturer is returning unexpected values:
1. Returning the value of `null` when the parameter should be omitted.
2. Returning a number instead of a string (I assume they are returning 0 or -1 instead of just leaving it blank?).
3. Returning an array when it should be a dictionary. I'm not sure if the array or dictionary has invalid values or isn't formatted correctly. 

This is what I am assuming from the bugs you are reporting. Like I said, if you could set a breakpoint and get the actual `RegisterAppInterface` response returned, it would greatly help with the debugging. Also, in other areas where it is crashing, it would be useful to see the actual response returned from SDL Core.

**Comment by mvyrko** [comment]
Hello @NicoleYarroch,
Unfortunately, I can't provide these information. I've got crashlogs from fabric, and we have no additional analytics information about head unit models.

**Comment by NicoleYarroch** [comment]
@mvyrko Is this true of all the bugs you are reporting or just this particular bug (#1159)

**Comment by mvyrko** [comment]
@mvyrko Yes, It's true of all the bugs

**Comment by joeygrover** [comment]
I believe the issue #1127 is releated with the same type of issue.

**Comment by kshala-ford** [comment]
@joeygrover kind of. This issue is about the root cause of #1127. The root cause wasn't fixed but the library was changed in the way to not perform a manager configuration update.

**Comment by joeygrover** [comment]
@kshala-ford right, I'm adding for visibility that the issue is related to unexpected data being sent from core and causing a crash in the library. The solution was a band aid fix on the single parameter rather than a library wide solution as seen in the check that was added `[actualLanguage isKindOfClass:[NSString class]]`. So it is the same root cause issue that should be addressed library wide rather than adhoc as the PR #1128 was to fix #1127
