### ISSUE TITLE
SDLManager are not disposed on disconnection

### ISSUE THREAD

**Issue by mjuarez-ford** [smartdevicelink/sdl_ios#1176]
### Bug Report
We noticed that when the phone is disconnected the SDLManager references are not disposed. So each time the user connects the phone or creates a new Instance of the SDLManager, degradation the performance of the application and causing possible problems.

In the following code, the SDLManager is created when the phone connects to the accessory ( but the issue happens also if the manager is created on the init)
You will also notice that on the method `managerDidDisconnect` we tried to stop the manager and setting it to nil but the references persist. 

``` objective-c
/*...*/ 
- (instancetype)init {
    self = [super init];
    if (!self) {
        return nil;
    }
    [[EAAccessoryManager sharedAccessoryManager] registerForLocalNotifications];    
    [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(createManager) name:EAAccessoryDidConnectNotification object:nil];
    
    return self;
}


- (void)createManager { 
/* Starts the manager */
/*...*/ 
}

/*...*/ 

- (void)managerDidDisconnect {
    NSLog(@"Manager disconnected!");
    dispatch_async(dispatch_get_main_queue(), ^{
        [self.sdlManager stop];
        self.sdlManager = nil;
    });
}
```
In the following image you can see the number of re-connections and how some objects are being referenced:

![screenshot 2019-03-07 at 10 58 43 am](https://user-images.githubusercontent.com/47789765/53956408-d231b800-40db-11e9-81d5-6b38af54141a.png)

**Comment by NicoleYarroch** [comment]
This appears to be an issue with your setup and not with the library itself. 

We recommend leaving the `SDLManager` alive throughout the life of the application . When I tested the SDL_iOS example app against Core, I can successfully set the `SDLManager` object to `nil` in the `managerDidDisconnect` method. 

I believe that your setup is not working because it can take a few seconds to close a `SDLManager` session as the `EASession` input and output sessions must be closed properly. The way you have it setup, both the `SDLManager` and your class are listening for `EAAccessory` notifications. When you get the notification, it looks like you are creating a new `SDLManager` object and starting it (I'm not sure as you do not have pseudo code in the example method).  Meanwhile the old `SDLManager` object is still shutting down so you get a `managerDidDisconnect` notification. 

Below I have included some very primitive code to show how you should wait for the current `SDLManager` to shutdown before creating a new `SDLManager` object.

```
- (instancetype)init {
    self = [super init];
    if (!self) {
        return nil;
    }

    self.destroyingSDLManager = false;
    self.createSDLManager = true;

    [[EAAccessoryManager sharedAccessoryManager] registerForLocalNotifications];
    [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(createManager) name:EAAccessoryDidConnectNotification object:nil];
    [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(destroyManager) name:EAAccessoryDidDisconnectNotification object:nil];

    return self;
}

- (void)createManager {
    if (self.destroyingSDLManager) {
        // You got a connect notification while the manager was shutting down, so wait until it has shut down compeletely before creating a new `SDLManager` object
        self.createSDLManager = true;
        return;
    }

    self.sdlManager = [[SDLManager alloc] initWithConfiguration:nil delegate:nil];
    [self.sdlManager startWithReadyHandler:^(BOOL success, NSError * _Nullable error) {
        if (!success) {
            SDLLogE(@"SDL errored starting up: %@", error);
            return;
        }
        // SDL manager started successfully
    }];
}

- (void)destroyManager {
    if (self.sdlManager == nil) { return; }
    self.destroyingSDLManager = true;
    [self.sdlManager stop];

    // Wait for the `managerDidDisconnect` delegate method to be called as it can take a few seconds to shut down the manager.
}

- (void)managerDidDisconnect {
    NSLog(@"Manager disconnected!");
    self.destroyingSDLManager = false;

    if (self.createSDLManager) {
        // It is now safe to create the new `SDLManager` object
        self.createSDLManager = false;
        [self createSDLManager];
    }
}
```

**Comment by NicoleYarroch** [comment]
Closing as this seems to be an implementation issue and not a library issue. 

If the issue persists, please re-open the issue and provide a more information.
