### ISSUE TITLE
Remove deprecated flag regarding to `fullAppId` from SDLRegisterAppInterface.h and SDLLifecycleConfiguration.h.

### ISSUE THREAD

**Issue by t-yoshii** [smartdevicelink/sdl_ios#1182]
### Bug Report
This is a serious backward compatibility problem. One of our OEM customers has already shipped SDL Core with v4.5. SDL Core v4.5 does not support `fullAppId` feature, therefore, appId must not be shortened by SDL proxy. If appId is shortened, SDL Core v4.5 cannot correctly compare the appId with Policy Table inside HU. If PT check does not work correctly, there is a risk of security and malfunction.

SDL Proxy must support RegisterAppInterface RPC and SDLLifecycleConfiguration without `fullAppId`.

##### Expected Behavior
SDL Proxy must support RegisterAppInterface RPC and SDLLifecycleConfiguration without fullAppId.

##### Observed Behavior
SDL Proxy treats these as deprecated.

##### OS & Version Information
* iOS Version: n/a
* SDL iOS Version: v6.1.0 and later

##### Test Case, Sample Code, and / or Example App
I will create PR.

**Comment by joeljfischer** [comment]
Hi @t-yoshii, we really need more information here. The changes made were agreed upon by the SDLC steering committee in a proposal review.

Why exactly is the existing `fullAppId` initializer not sufficient. It will automatically fill out the `appId` field with the exact text of the `fullAppId` field if the `fullAppId` contains no dashes and is limited to 10 characters or less. What is happening to cause this to be insufficient for you?

> SDL Core v4.5 does not support fullAppId feature, therefore, appId must not be shortened by SDL proxy.

This is very confusing to me. **Because** Core v4.5 doesn't support `fullAppId`, therefore, it **must** be shortened and placed into `appId`.

**Comment by t-yoshii** [comment]
Hello @joeljfischer, 
Thank you for your comment.

In our understandings, smartdevicelink.com issues UUID style appId after app registration at web portal.  UUID style appId has been issued before the `fullAppId` proposal (SDL 0153) is approved. Therefore, we recognize full-length UUID appId is also an officially supported appId style in RAI even in SDL Core v4.

Based on this understandings, we created Policy Table with full-length UUID appId.


When we use legacy (marked as deprecated) initializer of SDLLifecycleManager, full-length UUID is passed to RAI, and registered at SDL Core. This scenario is OK
Ex1)
appId: 123e4567-e89b-12d3-a456-426655440000
appId in RAI: 123e4567-e89b-12d3-a456-426655440000
appId in PT: 123e4567-e89b-12d3-a456-426655440000
=> No problem

On the other hand,  when we use new initializer of SDLLifecycleManager, a shortened UUID is passed to RAI, and registered at SDL Core. This scenario is *NG*
Ex2)
AppID: 123e4567-e89b-12d3-a456-426655440000
AppID in RAI: 123e4567e8
AppID in PT: 123e4567-e89b-12d3-a456-426655440000
=> NG (mismatch between RAI and PT!)

Therefore, we have to have an option to use full-length appId like Ex1 above.

**Comment by joeljfischer** [comment]
Unfortunately, removing this functionality would most likely cause issues with other partners, as we would be changing the agreed upon functionality to functionality that was not agreed upon. We will have to do more investigation to determine a viable solution.

**Comment by joeljfischer** [comment]
Is your policy server hardcoded? If not, you should be able to update your policy server. The only good solution here is to fix your policy server to return the correct ids.

You have to remember that altering this would change it for everybody. So if you tell an app to use the newly un-deprecated parameter, their app will be broken for other SDL enabled systems, which is not a good solution.

If you don't believe this is a workable solution, you would need to bring this up in the steering committee due to this being accepted behavior.

**Comment by t-yoshii** [comment]
> Is your policy server hardcoded? If not, you should be able to update your policy server. The only good solution here is to fix your policy server to return the correct ids.

PT in policy server can be modified dynamically. However, SDL Core loads initial PT from a local file. This file is hardcoded. If PTU uses OnSystemRequest, OnSystemRequest is not allowed by initial PT and PTU won’t work.


> correct ids

In our understanding, full-length UUID style appId is also correct ids.

**Comment by joeljfischer** [comment]
> PT in policy server can be modified dynamically. However, SDL Core loads initial PT from a local file. This file is hardcoded. If PTU uses OnSystemRequest, OnSystemRequest is not allowed by initial PT and PTU won’t work.

I don't think I'm following you here.

> In our understanding, full-length UUID style appId is also correct ids.

This is not correct, see the implemented proposal: https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0153-support-short-long-appid.md

Excerpts from the proposal:

> When an app registers with smartdevicelink.com, it is assigned an "appID" and a "fullAppID". The "fullAppID" will be the full UUID appID SHAID is currently generating. The "appID" string will be the first 10 non "-" characters of the full "fullAppID".

> If only the (short) appID is present in the RegisterAppInterface RPC request (legacy apps), sdl core shall use the (short) appID as the internal policy app id. i.e. use appID as the policy_app_id and use it to construct the icon path.

And the vote here: https://github.com/smartdevicelink/sdl_evolution/issues/443

Because the SDLC voted upon and agreed to the current behavior, we cannot revert this and use the unsupported behavior. If apps worked as you suggest by sending the full app id in the deprecated method, then their app will not function properly on the rest of the SDL ecosystem.

The behavior of your head unit and policy server is therefore unsupported. The only way to fix this will be to find a workaround on your policy server.

**Comment by E-SAITO-TMC** [comment]
Hi Guys,
I also understand that full-length UUID style appId is also correct ids.
If "appID" is really 10 characters, I do not know what the Full appID exists for.
It is not suggested that the policy server's refurbishment is so big.
Should Android Proxy keep old API like iOS Proxy and provide useful period?

**Comment by NicoleYarroch** [comment]
> If "appID" is really 10 characters, I do not know what the Full appID exists for.

As explained in the proposal for [supporting short and full UUID App Ids](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0153-support-short-long-appid.md) the `fullAppID` parameter is for the new UUID app id while the `appID` parameter is for legacy head units that have character limits for the app id. These legacy head units still need to be supported by SDL. If the `fullAppID` is set, Core will ignore the `appID` and use the `fullAppID` for determining app permissions.

**Comment by joeljfischer** [comment]
Closing for now. This is not an issue as phrased. If more discussion is required, I would advise discussion on the steering committee call.
