### ISSUE TITLE
Library Does Not Support Installation Via Swift Package Manager

### ISSUE THREAD

**Issue by joeljfischer** [smartdevicelink/sdl_ios#1387]
### Bug Report
Currently, the library does not support installation via Swift Package Manager due to SPM's inability to resolve submodules [see here for more info](https://forums.swift.org/t/package-with-git-submodule-doesnt-build-correctly/27852). We will have to move the submodule code into the library.

##### Reproduction Steps
1. Set up Xcode 11 with a sample app
2. Attempt to install sdl_ios via SPM

##### Expected Behavior
The imported package works correctly

##### Observed Behavior
The imported package fails to work correctly due to failures around the BSON lib.

##### OS & Version Information
* iOS Version: n/a
* SDL iOS Version: 6.4-develop
* Testing Against: Xcode 11

**Comment by thedavidharris** [comment]
I've got a working POC of this at https://github.com/thedavidharris/sdl_ios/tree/spm-support just adding some modulemaps to build bson in place with some symlinks, but there are a few caveats:

- SPM needs a public headers _path_, not them to be individually specificied as is. I can move all of these to /include, but it gets messy. Ideally, I think the whole folder structure of the project needs to be adjusted, as the current xcodeproj file is working off of folder references and any adjustments to support things like SPM would be a fair bit of work.
- In order to get around this, all the headers are public right now.
- There's an empty .swift file in the test target that needs to get removed, Swift and Objective-C can't be mixed in the same target.

If you want @joeljfischer I can continue plugging away at some of these, but that folder structure problem I didn't want to work out without consulting the team.

**Comment by joeljfischer** [comment]
Hi @thedavidharris, thanks for looking into this more. There's been an [open issue](https://github.com/smartdevicelink/sdl_ios/issues/568) for a long time to move the project to have public and private files in separate folders. That does eventually need to happen, we just keep putting it off. I think it would be a necessary part of having official SPM support.

> There's an empty .swift file in the test target that needs to get removed, Swift and Objective-C can't be mixed in the same target.

This seems to be a legacy file from when the quick testing library needed it. I deleted it locally and ran the tests and they seemed to work fine now. That could be removed.

> Doesn't add the Resource files or Localization yet

These are necessary because without them the lock screen won't work. I know that support for that is coming in Xcode 12, but I haven't looked deeper into it.

**Comment by thedavidharris** [comment]
All that sounds good. I'd agree that addressing #568 is a pre-requisite. After that, this should be able to flow through and still export the packages correctly, with the resources once Xcode 12 comes, so gives a little time.

What would be the ideal folder structure for the project? Something that mirrors the virtual folders in Xcode today but one layer deeper in public/private?

**Comment by joeljfischer** [comment]
I think that the folder structure would just be public and private, not mirroring the Xcode virtual folder structure. I worry that with additional public / private below the virtual structure it would get too messy and difficult to maintain.

**Comment by joeljfischer** [comment]
@thedavidharris Hello, #568 has been fixed and closed. Did you want to submit a PR for this? If so, there's a deadline of it being merged on 09/18, so we would need the PR submitted by 09/11, and you would need to be responsive to the PR review to get it done by our release deadline. 

Otherwise, I can take it on and fix it. If I do, do you mind if I re-use the work you did on that branch?

**Comment by thedavidharris** [comment]
Hey @joeljfischer , apologies been out for a few weeks. Likely won't get a chance to pick this up myself the next couple weeks (and our teams don't need any SPM support in the near-term), so if you're up for it definitely good to re-use some of this work.
