### ISSUE TITLE
The SDL Proxy does not send ChangeRegistration to the HU if users only change the hmiDisplayLanguage

### ISSUE THREAD

**Issue by zhouxin627** [smartdevicelink/sdl_ios#1491]
### Bug Report
The SDL Proxy does not send ChangeRegistration to the HU if users only change the hmiDisplayLanguage.

##### Preconditions
1. The app supports language changing
2. Default language settings:
The `hmiDisplayLanguage `is English
The vr/tts language is English

##### Reproduction Steps
Change the `hmiDisplayLanguage `to Japanese on the HU

##### Expected Behavior
The SDL Proxy sends `ChangeRegistration `to the HU

##### Observed Behavior
The SDL Proxy does not send `ChangeRegistration `to the HU

According to RPC Spec documents, it seems like when the HU's `hmiDisplayLanguage `or vr/tts language is different from the app's desired language, the app will send `ChangeRegistration `to change the registered language which is supported.
But at the SDL Proxy sourcecode's side, only the difference of vr/tts language will trigger `ChangeRegistration`.
The `hmiDisplayLanguage `and vr/tts language could be set separately in my use-case.

##### OS & Version Information
* iOS Version:12.3
* SDL iOS Version:6.3.0
* Testing Against:SDL Core 5.1.3 + HMI running on our development environment.

##### Occurrence:
100%

##### Recovery Method:
None

**Comment by joeljfischer** [comment]
Hi @zhouxin627, the issue seems to be that the sdl_ios library manager does not currently support updating to two separate languages, which seems to have been an oversight. In other words, the developer can only be told that the language updated, but not _which_ language type. That means that the `ChangeRegistration`, even if it's sent, wouldn't contain data for the two separate languages. What would occur in the situation you described in your issue would be that the developer would be told to update their language to Japanese, which would result in both HMI and VR/TTS data to be in Japanese after that point.

To fix this, a new `SDLManagerDelegate` method would need to be added:

```objc
- (nullable SDLLifecycleConfigurationUpdate *)managerShouldUpdateLifecycleToLanguage:(SDLLanguage)language hmiDisplayLanguage:(SDLLanguage)language;
```

and the old one should be deprecated:

```objc
- (nullable SDLLifecycleConfigurationUpdate *)managerShouldUpdateLifecycleToLanguage:(SDLLanguage)language;
```

Then the implementation must be updated to account for the new delegate method and to pass the HMI display language separately. This must all be done in a proposal.

**Comment by joeljfischer** [comment]
Closing because this must be fixed via a proposal
