### ISSUE TITLE
Insecure MD5 still used in SmartDeviceLink.framework

### ISSUE THREAD

**Issue by mtimmara** [smartdevicelink/sdl_ios#1673]
### Bug Report
Excerpt from app partner email:
_when we doing security scan for our app by DataTheorem, we found SmartDeviceLink.framework use MD5 ,  MD5 had deprecated,  it is insecure API,  I know you may not use MD5 in encrypt code or security related code, but DataTheorem report will public,  our customer may challenge it , so our security department require us must fix MD5 issue.  so I hope SmartDeviceLink can fix this issue rapidly._

-[SDLIAPTransport sdl_retryDelay] calls _CC_MD5()
-[SDLArtwork sdl_md5HashFromNSData:] calls_CC_MD5()

##### Observed Behavior
DataTheorem reports use of MD5.

##### OS & Version Information
* iOS Version: All
* SDL iOS Version: v 6.6.0
* Testing Against: DataTheorem

**Comment by joeljfischer** [comment]
Hi, thanks for reporting this. MD5 is not used for any cryptographic purpose. It is only used to create a unique string for an file name based on a file's data. There are no security implications for this. Second, this is not something that we can easily change. If we were to simply replace it with a "secure" (again, with no cryptographic purpose) hash generator, all the app's existing persistent uploads would remain there and would not be deleted or used.

**Comment by blzhu** [comment]
this MD5 defect may not related cryptographic purpose, but scan tool will not distinguish the purpose,the defect will still exist in their report, and public to everyone,  another side, customer also will not distinguish the purpose, they only believe use insecure API will cause security issue,  and competitors may also review this report,  any security issue may make waves in the market.
For hard to replace , I think it must have a solution to avoid, customers also will upgrade app for security reasons, and it also a chance to make SDL more secure.
so pls consider it again

**Comment by joeljfischer** [comment]
I'm sorry about the delay; I wanted to ensure that we had fully investigated possible solutions before responding.

I understand that you do not want DataTheorem reporting the use of MD5. You can avoid the use of MD5 in your application if you set all of your own file names (to avoid auto-name-generation using MD5).

This would very difficult to change at this point. In order to do so, we would have to design and develop a system that, when a developer updates their app, deletes any persistent files from the head unit and re-uploads them using a new hash mechanism. This is an invasive and rather complicated change that will slow down every user's experience of every app at least once, has additional complications, and should be avoided if at all possible. 

Replacing the timeout with another algorithm is similarly complicated because apps that previously did not have a collision may now have two separate distribution methods (between apps which have not updated and those which have) for their timeouts, increasing the likelihood of a collision. 

Because the usage of MD5 has no security implications whatsoever, I hope that we can come to an alternate solution.

**Comment by blzhu** [comment]
Thanks your explanation , I know your concern, but we also need to fix it , so I will replace MD5 in local,  if it works well , we will apply it in production.

**Comment by theresalech** [comment]
@blzhu, can you please provide more details on your plan to "replace MD5 in local"?  Does this mean you will set all of your own file names, as Joel suggested?

**Comment by joeljfischer** [comment]
Marking as wontfix and closing for now because this isn't an actual issue. We are not using md5 for any cryptographic use. This can be reopened if necessary.
