### ISSUE TITLE
PCM Audio Streaming stops for Nav app after phone call rejected

### ISSUE THREAD

**Issue by MichaelCrimando** [smartdevicelink/sdl_ios#1973]
### Bug Report
PCM Audio Streaming stops for Nav app after phone call rejected

##### Reproduction Steps
1. Connect an iPhone via USB and Bluetooth to SYNC
2. Run Antelope iOS test navigation app on SYNC. Tested on a Mustang Mach E (can provide .ipa)
2. Start a route while using PCM audio for directions
3. Have a different phone call the iPhone
4. Reject the phone call on SYNC
5. Observe that PCM audio no longer works

##### Expected Behavior
PCM Audio continues working after phone call

##### Observed Behavior
PCM Audio no longer works after phone call

##### OS & Version Information
* iOS Version: 14.4.2
* SDL iOS Version:  7.0.0
* Testing Against: SYNC4a v21073 r126 on a Mustang Mach E
* Antelope iOS v4.9

##### Test Case, Sample Code, and / or Example App
Attached Logs: I ran steps above and took VERBOSE level logs
"Antelope iOS Logs Voice TBT Issue.txt"
Then started a new log file and a new route just in case and took 
"Antelope iOS Logs voice doesnt work.txt"

[Antelope iOS Logs Voice TBT Issue.txt](https://github.com/smartdevicelink/sdl_ios/files/6320838/Antelope.iOS.Logs.Voice.TBT.Issue.txt)

[Antelope iOS Logs voice doesnt work.txt](https://github.com/smartdevicelink/sdl_ios/files/6320840/Antelope.iOS.Logs.voice.doesnt.work.txt)

**Comment by MichaelCrimando** [comment]
Related logs from sync side:
Looks like Antelope stopped the audio stream just after the incoming call.
``` # Incoming call started
Oct 28 17:37:14.802         AppLinkService.1147004               normal     25  10/28/2020 17:37:14.803/33837/23/AppLinkServiceOnProtocolIncomingCallEvent/1120/=SWHOOK:: Incoming Phone call event
Oct 28 17:37:14.803         AppLinkService.1147004               normal     25  10/28/2020 17:37:14.804/33844/29/static EPasStatus CAppLinkService::SendSDLMessage(HANDLE, const string&)/807/= JSON message2 [{
	"jsonrpc" : "2.0",
	"method" : "BasicCommunication.OnEventChanged",
	"params" : 
	{
		"eventName" : "PHONE_CALL",
		"isActive" : true
	}
}]

# AppLink notified the app about the call
Oct 28 17:37:15.407         AppLinkService.1147004               normal     25  10/28/2020 17:37:15.408/34030/29/EPasStatus CAppLinkService::OnSDLMessage(HANDLE)/366/= JSON message2 [{"id":95,"jsonrpc":"2.0","method":"Navigation.StopAudioStream","params":{"appID":8521}}

# The app stopped the audio streaming
Oct 28 17:37:15.408         AppLinkService.1147004               normal     25  10/28/2020 17:37:15.409/34041/29/static EPasStatus CAppLinkService::SendSDLMessage(HANDLE, const string&)/807/= JSON message2 [{
	"id" : 95,
	"jsonrpc" : "2.0",
	"result" : 
	{
		"code" : 0,
		"method" : "Navigation.StopAudioStream"
	}
}]
```




When the call was ended, SDL did not send notification to AppLink to start audio streaming again:
```
# The call ended
Oct 28 17:37:25.286         AppLinkService.1147004               normal     25  10/28/2020 17:37:25.287/36685/23/AppLinkServiceOnProtocolIncomingCallEvent/1120/=SWHOOK:: Incoming Phone call event

# AppLink notified SDL that the call had ended
Oct 28 17:37:25.287         AppLinkService.1147004               normal     25  10/28/2020 17:37:25.287/36692/29/static EPasStatus CAppLinkService::SendSDLMessage(HANDLE, const string&)/807/= JSON message2 [{
	"jsonrpc" : "2.0",
	"method" : "BasicCommunication.OnEventChanged",
	"params" : 
	{
		"eventName" : "PHONE_CALL",
		"isActive" : false
	}
}]
```

**Comment by NicoleYarroch** [comment]
@MichaelCrimando Thanks for reporting this issue. We would like to get this fixed as soon as possible. I am having difficulty reproducing so I hope you can provide more steps to help me fix the issue.

1. How does the  _Antelope_ app decide to stop the audio stream and then restart it?
    1a. Is it subscribed to the `SDLManagerDelegate`'s `audioStreamingState:didChangeToState:` method? If so, in what `SDLAudioStreamingState`s is the audio started and stopped?
    1b.  Is it subscribed to the `SDLManagerDelegate`'s `hmiLevel:didChangeToLevel:` method? If so, in what `SDLHMILevel`s is the audio started and stopped?
    1c. Is it listening for the `SDLAudioStreamDidStartNotification` and `SDLAudioStreamDidStopNotification` notifications in order to start and stop audio?
1. In order to play audio data are you using either of stream manager methods? I tried both and was not able to reproduce the issue. 
    2a. `sdlManager.streamManager?.audioManager.push(with: audioData)` 
    2b. `sdlManager.streamManager?.sendAudioData(audioData)`.

When testing on SYNC 3.0, I tried both rejecting the phone call and picking up the call and cancelling it. Both times the PCM audio resumed as expected every time I tested. I noticed that in your logs when the `hmiLevel` changes to `LIMITED` the `audioStreamingState` changes to `NOT_AUDIBLE`. This does not happen on SYNC 3.0. Rather the `audioStreamingState` stays in the `AUDIBLE` state. I will have to investigate if the state machine in the `SDLAudioStreamManager` is not handing that situation but it would be helpful if you could give me some more information to guide testing. Also the .ipa file would be really helpful.

**Comment by MichaelCrimando** [comment]
@NicoleYarroch Thanks for checking! Heres the answers: 
1a Thats not being used
1b. We dont use that for anything audio streeaing related
1c. Thats not being used

2. Currently Antelope doesnt use either of those. It uses `sdlManager.streamManager?.audioManager.push(withFileURL: theFile)` and `sdlManager.streamManager?.audioManager.playNextWhenReady()`

Is the way you mentioned more modern?

**Comment by NicoleYarroch** [comment]
@MichaelCrimando I am a little stumped. I double checked that `sdlManager.streamManager?.audioManager.push(withFileURL:)` works with a rejected phone call and everything seems to be in working order. 

For question no.2 above, I just wanted to double check that you were using the `audioManager` to send the audio data and not the `streamManager`. 

I checked the _Antelope iOS Logs Voice TBT Issue.txt_ and I can't see any issues with state transitions. As far as I can tell, the library never requests to stop the audio transport, so that isn't the reason why audio can't stream. You wouldn't happen to have set the the `audioManager.delegate` and implemented the `SDLAudioStreamManagerDelegate`? I'm not sure if the data simply isn't getting sent or if some error happened while it was getting sent, so seeing which `SDLAudioStreamManagerDelegate` methods are being called would be helpful. I can't see any verbose logs in 
_Antelope iOS Logs Voice TBT Issue.txt_ so I am just trying to think of things that might have gone wrong. 

Is it possible for you to re-run the steps again with SDL verbose logs on?

**Comment by MichaelCrimando** [comment]
@NicoleYarroch  hmmm we do use `SDLAudioStreamManagerDelegate` thought not a whole lot of code around here. Heres the complete extension

```swift
//MARK: SDLAudioStreamManagerDelegate
extension ProxyManager: SDLAudioStreamManagerDelegate{
    public func audioStreamManager(_ audioManager: SDLAudioStreamManager, errorDidOccurForFile fileURL: URL, error: Error) {
        
    }
    
    public func audioStreamManager(_ audioManager: SDLAudioStreamManager, fileDidFinishPlaying fileURL: URL, successfully: Bool) {
        audioManager.playNextWhenReady()
    }
}
```

**Comment by NicoleYarroch** [comment]
@MichaelCrimando I tried setting `audioManager.playNextWhenReady()` in the `audioStreamManager:fileDidFinishPlaying:successfully:` delegate method but I wasn't able to reproduce the issue still. 

As far as I can tell during my testing, the SYNC 3.0 module does not send any sort of notification to the library when a phone call occurs. Do you know if this behavior is different on SYNC 4.0?

**Comment by MichaelCrimando** [comment]
@NicoleYarroch  ahhh interesting observation. I dont have a SYNC3 to try on, but my colleague does. They the same test scenario on SYNC 3 v3.4 Build 21063_DEVTEST and PCM works fine there. So is this more likely that the SYNC4 software is doing something incorrectly? It sounds like its ending the audio stream when it shouldnt

**Comment by NicoleYarroch** [comment]
Since I don't see any `OnHMIStatus` notifications that seem out of the norm in the logs you posted and you've confirmed that you are not starting and stopping the audio based on information received in the `OnHMIStatus` notifications, I'm inclined to think that there is a bug with the SYNC 4 HMI restarting audio after the phone call is rejected.

**Comment by MichaelCrimando** [comment]
Ok reported to SYNC
