### ISSUE TITLE
Calling SDLDeleteInteractionChoiceSet always return resultCode = "IN_USE"

### ISSUE THREAD

**Issue by 84798012** [smartdevicelink/sdl_ios#1976]
I have made SDLCreateInteractionChoiceSet and SDLPerformInteraction, then it will show my list page.
Then I return to main page and goto list page again, now the list count and content have changed.
So I called SDLDeleteInteractionChoiceSet before goto list page in order to remove old ChoiceSets and then create new ones.
But I always get the failed result with resultCode = "IN_USE".

Could you help on this issue, is there anything wrong ?
Thank you!

**Comment by NicoleYarroch** [comment]
We would highly recommend that you start using the choice set menu manager to [create and present your menu](https://smartdevicelink.com/en/guides/iOS/displaying-a-user-interface/popup-menus/#popup-menus) instead of creating and sending the RPCs yourself as there are a lot of edge cases to think of.

Otherwise, I would make sure that you implement the `systemContext:didChangeToContext:` method on the `SDLManagerDelegate` and make sure that you are not in `SDLSystemContextMenu` when you send the `SDLDeleteInteractionChoiceSet` requests. I would also make sure that you wait for a response to your `SDLPerformInteraction` and/or `SDLCreateInteractionChoiceSet` requests before trying to delete any of the choice set items.

**Comment by 84798012** [comment]
[cantDeleteIssue.txt](https://github.com/smartdevicelink/sdl_ios/files/6383499/cantDeleteIssue.txt)
Since we have legacy code, is there a way to delete rightly using InteractionChoiceSet ?
Seems I'm not in "SDLSystemContextMenu" when send delete. And how to stop waiting for a response to my SDLPerformInteraction and/or SDLCreateInteractionChoiceSet requests?
Here attached my code and log.
If there is no way to handle this, I will try to see if can modify the old code using choice menu.

**Comment by NicoleYarroch** [comment]
@84798012 I tried testing with similar code to what you posted in **cantDeleteIssue** and did not have any issues with deleting a choice set with sdl_core v.7.1.0 (RPC spec v.7.1.0) or SYNC 3.0 (RPC spec v.4.2). If I tried to delete the interaction choice set before I got a response to the `SDLPerformInteraction` request, I did get an `IN_USE` error.

I would make sure you have a response to the `SDLPerformInteraction` request before you try to send the `SDLDeleteInteractionChoiceSet`. An example of how to do that is:
```
sdlManager.send(request: SDLCreateInteractionChoiceSet) { [weak self] request, response, error in
    self?.sdlManager.send(request: SDLPerformInteraction, responseHandler: { [weak self] request, response, error in
        // Don't send the SDLDeleteInteractionChoiceSet until you have gotten a response to the SDLPerformInteraction request
        self?.sdlManager.send(request: SDLDeleteInteractionChoiceSet) { [weak self] request, response, error in
        }
    })
}
```

There is a possibility that the issue lies with your emulator/module. You could try testing with Manticore (https://smartdevicelink.com/sign-in/?next=/resources/manticore/) to see if you get the same response to a `SDLDeleteInteractionChoiceSet`.

**Comment by 84798012** [comment]
Thanks Nicole.
I did delete the interaction choice set after I got a response to the SDLPerformInteraction request.
In my head unit (SYNC 3.0 build17110_devtest), it will got IN_USE error.
But in the manticore link you supply do test, it works well.
So I think it may be the old version head unit got this issue, if user use new version head unit, it should be fine.
