### ISSUE TITLE
SDLIAPTransport dispatch_sync should be a dispatch_async

### ISSUE THREAD

**Issue by joeljfischer** [smartdevicelink/sdl_ios#229]
In `-[SDLIAPTransport controlStreamHasBytesHandlerForAccessory:]` there is a `dispatch_sync` back to the main queue. This seems that it could be a `dispatch_async`, I am not sure why the current queue has to block until the data session is created.

**Comment by joeljfischer** [comment]
https://github.com/smartdevicelink/sdl_ios/blob/release/4.0.0/SmartDeviceLink-iOS/SmartDeviceLink/SDLIAPTransport.m#L189

**Comment by justinjdickow** [comment]
@adein To find out more information based on their internal source

**Comment by adein** [comment]
So, the only comment in the commit that changed it is this: "Moved most transport processing back on to main thread. Removed most GCD dispatches."

Prior to that, the call to createIAPDataSessionWithAccessory:forProtocol: was made directly, which resulted in it being called in a separate queue/runloop (whatever one the controlStreamDelegate.streamHasBytesHandler ran in).  I'm assuming this was to fix an issue with the protocol index not being processed correctly or in a timely fashion, but that's just a guess.

So the _sync is because the previous call was a direct method call.  And it was changed to a dispatch in order to run the method on the main thread instead of whatever background thread it was on.  I can't say if this is necessary or not, though.
