### ISSUE TITLE
Proxy allows attempting to send an RPC when not connected

### ISSUE THREAD

**Issue by joeljfischer** [smartdevicelink/sdl_ios#241]
See #238

**Comment by adein** [comment]
If this could be fixed as a hotfix, it would be another one I'd like to get in ASAP if possible.  It allows developers to create apps that will never be able to reconnect to SYNC until they are terminated and relaunched.  At the same time, it's not easy for devs to root-cause the connection issue.

If we're only making it so that the proxy uses a BOOL to track connection state and prevent sending an RPC when not connected, I think it should be a pretty easy/quick change.

**Comment by joeljfischer** [comment]
Yeah, probably a BOOL within the `sendRPC:` method of `SDLProxy` would be sufficient. The proxy isn't currently set up to know whether or not it's connected because it's assumed to be destroyed if not connected however, so that would be a bit of a change to make that work well.

**Comment by adein** [comment]
In my testing, I made a class BOOL (readonly public, readwrite private), that gets updated in the onProxyClosed / onProxyOpened events before the proxy listener delegate is called.
