### ISSUE TITLE
Variable activeSystemRequestTasks in class SDLProxy is never instantiated.

### ISSUE THREAD

**Issue by anildahiya** [smartdevicelink/sdl_ios#259]
During code analysis we observed that -

Variable activeSystemRequestTasks of type NSMutableSet in class SDLProxy is never instantiated and hence no memory is allocated to it. So, it's not active for its references in SDLProxy class ex- handleSystemRequestQueryApps :(SDLOnSystemRequest *) request.

https://github.com/smartdevicelink/sdl_ios/blob/release/4.0.0/SmartDeviceLink-iOS/SmartDeviceLink/SDLProxy.m

Ideally its reference should be either removed from this class or we need to instantiate this variable for its intended usage.

**Comment by joeljfischer** [comment]
I think this happened with the big merge as well.

**Comment by adein** [comment]
Can we just remove the relevant code altogether?  I'm not sure what it's for, and it doesn't seem to have any effect anyway..

**Comment by joeljfischer** [comment]
It's used for the query apps URL request. It holds on to the NSURLSessionTask until that task completes. Until then, you can use the task to cancel the URL request. Since this whole feature is likely to be broken in iOS 9, it could be removed when that feature is removed. The task isn't being used right now, but we could add more advanced behavior such as cancelling or retrying if the task isn't working properly.

That was the idea behind it anyway.
