### ISSUE TITLE
Minimum iOS version supported is 8.0

### ISSUE THREAD

**Issue by adein** [smartdevicelink/sdl_ios#268]
This requires app developers to only support 8+ if they use the SDK.  Many app developers wish to support as early as 5 or 6, and are not happy about this (new) requirement. The only 2 instances we've found that require iOS 7/8 are avoidable.  They are:

1. Using NSURLSession (as opposed to supporting NSURLSession and NSURLConnection)
2. Using beginBackgroundTaskWithName (as opposed to beginBackgroundTaskWithExpirationHandler)

Pull requests will be added soon.

**Comment by joeljfischer** [comment]
Quick comment is that even though the framework target's minimum version is 8.0 because that's the minimum for frameworks, the minimum for the Cocoapods is currently 7.0, and it can go lower. So as long as the code itself is compatible with pre-7.0, we can change the podspec to allow lower than 7.0. The framework target would have to remain 8.0. We could theoretically add a static lib target that targets lower than 8.0 as well, if it becomes needed. Let me know if that makes sense haha.

**Comment by adein** [comment]
Are we using dynamic framework linking for some reason?  That's only required if you're including/linking against another framework from within ours..?

**Comment by joeljfischer** [comment]
I'm not sure what you mean. I was talking about the library itself generating a dynamic framework; it currently isn't linking other frameworks in. Eventually the idea is that it will link frameworks in, i.e. for the logging framework which would be an 'outside' project that's linked in. Dynamic framework linking is nice because it can be runtime / optional. Cocoapods also allows us to have dependencies like this as well (for 7.0 or less). However, a static target wouldn't allow for this, and I'm not sure what the solution would be.

**Comment by adein** [comment]
Correct.  We've always used a static framework in the past because that's all that was supported in earlier versions of iOS.

We can't just tell developers that their apps will only work on 8 and later with our SDK.  Even though a large percentage of users (at least in the US) update to the latest iOS, there are still users (especially in other markets like Asia) that cannot or will not update, and many app developers target those regions/audiences.

We need some sort of solution to support iOS (5 or 6, ideally 5)+; whether it's creating a duplicate/static version of the framework or something else.

**Comment by joeljfischer** [comment]
Right, that's what Cocoapods is meant to cover, it can go back as far as we need to. I realize that we may have to create a static version, I was just hoping to wait for developers to complain before doing it, because it's so much extra work compared to Cocoapods & dynamic frameworks.

**Comment by adein** [comment]
We currently have developers reporting issues against our previous (AppLink 2.3.2) SDK as they're upgrading to it because it is only iOS 7+, and they want to support 5+ like before.  So we definitely need this for this 4.0 release.

Currently I'm assigned, but I'm not familiar enough with Cocoapods to do this.  However, I can help someone with the static library creation if needed.

**Comment by joeljfischer** [comment]
Well, as long as the code supports pre-7.0, it's just a matter of changing [this line](https://github.com/smartdevicelink/sdl_ios/blob/release/4.0.0/SmartDeviceLink-iOS.podspec#L9) to say '6.0' or '5.0' or whatever we support. I think we need to support 6.0+ because we're not using dispatch_release()?

**Comment by adein** [comment]
We should have a pull request soon that addresses the iOS 7+ code issues (except for creating the static library).

**Comment by joeljfischer** [comment]
There's another issue with iOS 6.0. See here:
https://github.com/smartdevicelink/sdl_ios/blob/release/4.0.0/SmartDeviceLink-iOS/SmartDeviceLink/SDLPolicyDataParser.m#L18

Built-in Base64 encoding is only available in iOS 7+. To get it in 6.0 we'll need to integrate a library :sob:

**Comment by adein** [comment]
@joeljfischer Previously the SDK supported iOS 5+, so I'm curious how it was done before.  We could look at the old/internal repo and see if there's anything useful there..

**Comment by joeljfischer** [comment]
@adein I found a way to subvert it without needing a library. When Apple introduced base64 in iOS 7 they also introduced immediately deprecated methods that had previously been available but private. See [this commit](https://github.com/smartdevicelink/sdl_ios/commit/79be3f601e7199798e778fb523662324cb486d5f) where I fix the issue.

**Comment by adein** [comment]
Oh, great.  So we don't need another library then?

**Comment by joeljfischer** [comment]
No, we're set there.
