### ISSUE TITLE
Modify SDLProtocol buffer size to reduce memory usage

### ISSUE THREAD

**Issue by joeljfischer** [smartdevicelink/sdl_ios#270]
https://github.com/smartdevicelink/sdl_ios/blob/release/4.0.0/SmartDeviceLink-iOS/SmartDeviceLink/SDLProtocol.m#L204

I'm guessing there's a reason for this?

**Comment by justinjdickow** [comment]
@adein this was left alone in #272, but it may need to be addressed because we're talking about a 512k buffer size now for received bytes.

This could be an artifact of 1024 being used on iOS as the MTU while Core was using 1500?

**Comment by adein** [comment]
@justinjdickow @joeljfischer 

Based on a quick skim, it looks like the size is arbitrary (especially without any comments).  Whenever new data comes in, the data is appended to the buffer (self.receiveBuffer) and then processMessages: is called.  The processMessages: method will look for a *full/intact* message in the buffer and pull it out and process it.  So if a message is larger than the MTU, you'll have multiple calls to handleBytesFromTransport: and processMessages: that simply append data to the buffer until the full message is in the buffer.  At which point the next processMessages: will actually pull out the message.

Since it's an NSMutableData object, it will expand as needed (i.e., for a large PutFile).  I don't know if you get any performance boost at all by using initWithCapacity:, or if allowing the object to scale automatically will be exactly the same performance.  It could be changed to a simple init if desired, and the only thing that *could* change would be performance (maybe).

**Comment by joeljfischer** [comment]
Right, so if an NSMutableData needs to increase in size, there is a small performance penalty. So basically: 

1. Have a fairly small performance hit by re-init-ing the data in a size equivalent to the MTU size (or smaller if we wanted) and allow it to expand if needed, but then it will be discarded and recreated when a new packet comes in.
1. Keep one mutable data that is erased, but it will be in permanent memory as large as the largest RPC (including multiple packets) we've received.

I'd tend toward the former I think.

**Comment by adein** [comment]
I'm fine with the first one as long as there's logic to make sure the buffer is empty (i.e., no partial message left over) before discarding and re-creating.

**Comment by justinjdickow** [comment]
@joeljfischer Is this question sufficiently answered?

**Comment by joeljfischer** [comment]
@justinjdickow I just modified the title and label to no longer be a question.
