### ISSUE TITLE
framework released not support i386 and x86_64

### ISSUE THREAD

**Issue by parametersky** [smartdevicelink/sdl_ios#322]
I have integrated sdl to my app, before that i always debug my app on simulator.  i hope the framework can support i386 and x86_64 to running on a simulator.

**Comment by joeljfischer** [comment]
Hi @parametersky, I'm not sure why that would be. The example app in the repository builds the same framework and runs in the simulator. I'm going to need more information to be able to help. Can you tell me how you are retrieving and integrating the project, and the errors you are getting?

**Comment by joeljfischer** [comment]
After further investigation, I found the answer. The reason why we don't ship releases with simulator slices is because of this radar: http://www.openradar.me/radar?id=6409498411401216

If we ship a framework with simulator slices, you won't be able to submit to the app store unless you use a special workaround built into Carthage. As not everybody will use Carthage, we thought it best to leave simulator out.

This leaves you with only two options, unfortunately:

1. Build the project yourself for the arches you need, and make sure to remove simulator slices before shipping.
2. Only test on a device.
