### ISSUE TITLE
Update SDK to include AppInfo struct parameter in RAI request

### ISSUE THREAD

**Issue by mrapitis** [smartdevicelink/sdl_ios#398]
We need to update the SDK to include the new AppInfo struct that includes a bundleID used for remote app launching strategies.  Please see attached xml doc for details.
[AppLink_Mobile_API_v4_x _withAppInfo.zip](https://github.com/smartdevicelink/sdl_ios/files/263271/AppLink_Mobile_API_v4_x._withAppInfo.zip)

**Comment by justinjdickow** [comment]
What mobile api version is this supposed to be supported in? In SDL Core it's not in the master or develop branches in the MOBILE_API xml.

**Comment by joeljfischer** [comment]
This needs way more information. Why is this needed? What is the impact on existing apps and head units? Is there a prototype? What are the upsides and downsides? Were other solutions considered? What must be implemented on head units? etc. 
Something more akin to this: https://github.com/apple/swift-evolution/blob/master/proposals/0027-string-from-code-units.md

Please also include a snippet of the change instead of the whole file.

**Comment by joeljfischer** [comment]
Fixed in #431
