### ISSUE TITLE
SDLJingle 'constants' should be constants.

### ISSUE THREAD

**Issue by justinjdickow** [smartdevicelink/sdl_ios#7]
currently defined as

```
+(NSString*) NEGATIVE_JINGLE { return @"NEGATIVE_JINGLE"; }
+(NSString*) POSITIVE_JINGLE { return @"POSITIVE_JINGLE"; }
+(NSString*) LISTEN_JINGLE { return @"LISTEN_JINGLE"; }
+(NSString*) INITIAL_JINGLE { return @"INITIAL_JINGLE"; }
+(NSString*) HELP_JINGLE { return @"HELP_JINGLE"; }
```

see #3 for more information

**Comment by asm09fsu** [comment]
This will be resolved in PR #447. Can we close this @joeljfischer ?

**Comment by joeljfischer** [comment]
Just mention that this is fixed in #447 then

**Comment by asm09fsu** [comment]
@joeljfischer actually, after looking at this again, `SDLJingle` has no reason to exist anymore. This is because [`SDLPrerecordedSpeech`](https://github.com/smartdevicelink/sdl_ios/blob/master/SmartDeviceLink/SDLPrerecordedSpeech.h) contains these exact same constants. Is there another reason this exists?

**Comment by joeljfischer** [comment]
Don't think so. Needs a prop to remove probably...

**Comment by joeljfischer** [comment]
Or, it's probably covered by the enum proposal.

**Comment by asm09fsu** [comment]
This will be removed in #447

**Comment by asm09fsu** [comment]
This has been removed in develop.
