### ISSUE TITLE
iOS App crash after starting iAP control session

### ISSUE THREAD

**Issue by kshala-ford** [smartdevicelink/sdl_ios#887]
### Bug Report
App crash after starting iAP control session. The issue was reported externally but could not be reproduced yet. Based on the stack trace the app tried to create an iAP control session and it crashed at `EASession initWithAccessory:forProtocol:]`.

##### Reproduction Steps
1. Connect iPhone over USB
2. ¯\_(ツ)_/¯ (will be provided once we can reproduce)

##### Observed Behavior
App did crash when creating an `EASession` object.

##### OS & Version Information
* iOS Version: 11.2.5
* SDL iOS Version: 5.0.0
* Testing Against: TBD

##### Test Case, Sample Code, and / or Example App
[crash.txt](https://github.com/smartdevicelink/sdl_ios/files/1781243/crash.txt)

**Comment by joeljfischer** [comment]
Hi @kshala-ford, do we have any more information on this? Is it reproducible on 5.1.0 or 5.2.0-develop? I've seen this bug as well, it happens rarely, but it seems to be a bug with Apple's EA system. It literally happens when attempting to init an object. We could perhaps try-catch around it to prevent the crash, but since this does not appear to be an exception, I'm not sure it would even catch it.
