### ISSUE TITLE
Fix inconsistent capitalization of `SDLVrCapabilities` 

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/sdl_ios#939]
### Bug Report
In parts of the project `SDLVRCapabilities` is spelled *SDLVRCapabilities* and in others *SDLVrCapabilities*. The correct format is *SDLVrCapabilities*.

##### OS & Version Information
* iOS Version: n/a
* SDL iOS Version: 5.3
* Testing Against: n/a

**Comment by joeljfischer** [comment]
This is closed as a Won't Fix.

The spec incorrectly capitalizes `VR` (Voice Recognition) as `Vr`, so the file names match the spec, but the class names are correct because they can be. This can’t really be fixed without major version / proposals. It is not inconsistent if you take file names as matching the spec, and everything else as correctly capitalizing `VR`.
